// skillsData.ts
export const skillsData = [
  "React",
  "TypeScript",
  "JavaScript",
  "HTML5 & CSS3",
  "AngularJS",
  "Node.js",
  "Express.js",
  "MongoDB",
  "PostgreSQL",
  "GraphQL",
  "C++",
  "C#",
  ".NET",
  "Python",
  "Sketch",
  "SolidWorks",
  "Git",
  "Scrum",
  "Agile",
  "Test Driven Development (TDD)",
  "Vite",
  "React Testing Library",
  "Google Drive",
  "Dropbox",
  "OneDrive",
  "HTML Canvas",
  "CNC Machining",
  "Embedded Development",
];
